### ISSUE TITLE
Adding step 4.0 to WELD.md

### ISSUE THREAD

**Issue by gwaybio** [broadinstitute/pooled-cp-profiling-template#17]
@hillsbury and I noticed that there should be a step 4.0 before step 4.1:

```bash
conda env create --force --file environment.yml
```

**Comment by ErinWeisbart** [comment]
Conda environment creation is in SETUP so it doesn't need to be in WELD.
I added a sentence to WELD to clarify that SETUP must be performed first in https://github.com/broadinstitute/pooled-cell-painting-profiling-template/commit/5ba34ef3008dc5c2bafea2615614bd5a493913b9
