### ISSUE TITLE
Conda environment install not working

### ISSUE THREAD

**Issue by ErinWeisbart** [broadinstitute/pooled-cp-profiling-template#8]
Tried installing conda environment on a new (Windows) computer and got:

```
Solving environment: failed

ResolvePackageNotFound:
  - conda-forge::scipy=1.4.1
```

**Comment by ErinWeisbart** [comment]
It also gives this warning while attempting the install:
```
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.
```

**Comment by gwaybio** [comment]
The last warning is ok - I see it all the time even after adding `pip` - and it never breaks anything.

Also, looking at the [conda-forge scipy distributions](https://anaconda.org/conda-forge/scipy) it looks like windows versions are pretty far behind.

![image](https://user-images.githubusercontent.com/7340421/90827021-7d065800-e309-11ea-8214-c58686d10a7c.png)

Can you try replacing with `- conda-forge::scipy=1.3.2`?

---

Actually, after typing this I realize that we don't use `scipy` at all in the welding procedure. It is safe to remove to reduce dependencies!
